### ISSUE TITLE
Show which hypervisor a vm is on

### ISSUE THREAD

**Issue by hamptonmoore** [fosshostorg/aarch64#53]

**Comment by hamptonmoore** [comment]
also provide the v4 address of the hypervisor in the proxies tab so that users can configure A records correctly

**Comment by natesales** [comment]
The hypervisor itself is already exposed to the dashboard, so that would just take a little frontend code to concatenate `vm.pop` and `vm.host`. The IPv4 address is trickier since they live in a different collection. The best way to address this imho is to add a `vm.host_ipv4` field at VM creation time.
