### ISSUE TITLE
VM Allocation Options

### ISSUE THREAD

**Issue by alyx** [fosshostorg/aarch64#63]
Currently we show users all VM allocation options, including options they can't select as those choices would be above their allocated core count; perhaps we should limit the display to what options the user can actually allocate?

**Comment by knightss27** [comment]
While I can see why it isn't really useful to be able to select them and then try creating, if I am a project currently using most of my budget, but I want to be able to see whether I could afford a bigger one, wouldn't it be useful to show all of them, otherwise the user would have to delete their current VMs to be able to view the options? I think we could maybe just grey out options that are above the budget.

**Comment by alyx** [comment]
That seems reasonable; grey out + make the options unclickable so they're clearly "not available" while still being shown as things that exist may be ideal.

**Comment by knightss27** [comment]
Opinions?
![image](https://user-images.githubusercontent.com/52898165/129299758-20ae2039-01ae-4fc3-a270-6c3b1edc0970.png)
