### ISSUE TITLE
Change License to AGPL

### ISSUE THREAD

**Issue by lmtr0** [fosshostorg/aarch64#80]
Hello there, good morning.
I recently notice that this project uses GPL and it's a web application, however I think it would be better to use AGPL instead because AGPL contains some specif clauses that GPL doesn't contain to the non-release of source  code for web applications.

as stated "The AGPL's additional clause only applies when the user interacts with but does not receive the program." from [curiousdannii](https://opensource.stackexchange.com/users/190/curiousdannii) available in \<https://opensource.stackexchange.com/questions/4303/is-there-any-difference-between-the-gpl-and-agpl-for-code-executed-in-the-browse \>

**Comment by cauerego** [comment]
i learned about agpl a few months ago, and i work completely in favour of it.

every software should always use agpl+, honestly.

i still couldn't find a better license, and all of the other big ones, including wtfpl and gpl3, will inevitably do more harm than good to the world. because they can, they are, and they will be abused.

for each its own.

to me, building code without paying attention to why is exactly like building a house without knowing if anyone will even ever live there: a waste of precious resources.

this gets specially harmful when done under any kind of "free" speech, aiming for freedom.

android is free and open source. chromium. etc.

**Comment by lmtr0** [comment]
I couldn't agree more. Well said

**Comment by hamptonmoore** [comment]
I've instructed the team to thumbs up this post if they approve of the change

**Comment by mplscorwin** [comment]
I assume you mean the issue itself, vs any connect, ye?

**Comment by hamptonmoore** [comment]
Repo has been moved to AGPL after developer feedback. Thank you!

**Comment by lmtr0** [comment]
Nice

**Comment by cauerego** [comment]
wonderful indeed!!

now let us hope it won't go rogue like mongodb... unless their new license indeed is better than agpl (i really can't tell for sure, but it looks like just bad rewording to me).

ping back https://talk.ahoxus.org/notice/AG0Wcn4B7rgv7buyCu

**Comment by lmtr0** [comment]
I didn't know about that
